project:
  type: book

book:
  title: "Statistical Rethinking notes and exercises"
  author: "Zane Billings"
  date: "6/21/2022"
  chapters:
    - index.qmd
    - cp1.qmd
    - cp2.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo



