project:
  type: book
  output-dir: docs
  output-file: "Zane-SR-Notes"

book:
  title: "Statistical Rethinking notes and exercises"
  author: "Zane Billings"
  date: "6/21/2022"
  repo-url: https://github.com/wzbillings/SR-notes/
  repo-actions: [issue, source]
  sharing: [twitter]
  search: true
  chapters:
    - index.qmd
    - cp1.qmd
    - cp2.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: pulse
      dark: vapor



