project:
  type: book
  output-dir: docs

execute: 
  freeze: auto

book:
  title: "Statistical Rethinking notes and exercises"
  author: "Zane Billings"
  date: "6/21/2022"
  output-file: "Zane-SR-Notes"
  repo-url: https://github.com/wzbillings/SR-notes/
  repo-actions: [issue, source]
  sidebar:
    search: true
    tools:
      - icon: house-door-fill
        href: https://wzbillings.com
      - icon: mastodon
        href: https://fediscience.org/@wzbillings
  search: true
  chapters:
    - index.qmd
    - part: "Textbook"
      chapters:
        - cp1.qmd
        - cp2.qmd
        - cp3.qmd
        - cp4.qmd
        - cp5.qmd
    - part: "2023 Homework"
      chapters:
        - week1.qmd
        - week2.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: pulse
      dark: vapor



