---
output: html_document
editor_options: 
  chunk_output_type: console
---
# The Many Variables and the Spurious Waffles

This chapter discusses the "causal salad" issue that is really prevelant in epidemiology (and other sciences) right now. When you "adjust" for variables in models, what are you actually doing? What answers can you get from adjusting? How do you decide what variables should go into a model? We get to talk about confounding, which is one of my favorite subjects, and more generally, other types of biases. These are presented in the framework of graphical causal models using directed acyclic graphs (DAGs).

## Chapter notes



## Exercises

**5E1.** The linear models

$$\mu_i = \beta_x x_i + \beta_z z_i$$
and
$$\mu_i = \alpha + \beta_x x_i + \beta_z z_i$$

are both multiple regression models. The first model
$$\mu_i = \alpha + \beta x_i \right)$$
is a simple linear regression model and while the third model
$$\left( \mu_i = \alpha + \beta (x_i - z_i) \right)$$
involves both $x$ and $z$, the model only has one coefficient and treats their difference as a single explanatory variable.

**5E2.** We could evaluate the claim *animal diversity is linearly related to latitude, but only after controlling for plant diversity* using the linear model
\begin{align*}
\text{animal diversity}_i &\sim \mathrm{Likelihood}\left( \mu_i \right) \\
\mu_i &= \alpha + \beta_1 \left( \mathrm{latitude} \right) + \beta_2 \left( \text{plant diversity} \right)
\end{align*}

where suitable priors are assigned and other appropriate parameters are given for the likelihood function.

**5E3.** We could evaluate the claim *neither amount of funding nor size of laboratory is by itself a good predictor of time to PhD degree; but together these variables are both positively associated with time to degree* using the multiple linear regression
\begin{align*}
\mathrm{time to PhD}_i &\sim \mathrm{Likelihood}\left( \mu_i \right) \\
\mu_i &= \alpha + \beta_1 \left( \text{amount of funding} \right) + \beta_2 \left( \text{size of laboratory} \right)
\end{align*}

with suitable priors, etc. The slope of both $\beta_j$ should be positive. Classically, I would probably be inclined to include an interaction term in this model, but we haven't talked about that yet in the book so I didn't.

**5E4.** If we have a single categorical variable with levels $A,$ $B,$ $C,$ and $D,$ (represented as indicator variables), the following linear models are inferentially equivalent:
\begin{align*}
\mu_i &= \alpha + \beta_A A_i + \beta_B B_i + \beta_D D_i, \\
\mu_i &= \alpha + \beta_B B_i + \beta_C C_i + \beta_D D_i, \\
\mu_i &= \alpha_A A_i + \alpha_B B_i + \alpha_C C_i + \alpha_D D_i, \quad \text{ and }\\
\mu_i &= \alpha_A \left( 1 - B_i - C_i - D_i \right) + \alpha_B B_i + \alpha_C C_i + \alpha_D D_i.
\end{align*}

**5M1.** An example of a spurious correlation: I am happy on days when it is sunny outside, and when I get to leave work early. Both of these things individually make me happy, but the weather doesn't determine whether I get to leave work early. (At least not fully anyways. The weather definitely determines how much work I get done, but other external factors control the amount of work I have and the deadlines I need to meet.)

**5M2.** An example of a masked relationship: fill this in when I think of one.

**5M3.** I guess a higher divorce rate could cause a higher marriage rate by making more people available to be married. If divorced people tend to get remarried (potentially to non-divorced people), then the overall marriage rate could go up. Addressing this using a simple multiple regression model would be quite difficult, as you would need more data on remarriage and divorce status.

**5M4.** I found [this list](https://worldpopulationreview.com/state-rankings/mormon-population-by-state) of percent LDS population by state. So if we want to add this as a predictor to the divorce rate model, first I'll join these data to the WaffleDivorce data from the `rethinking` package.

```{r}
pct_lds <- readr::read_csv(here::here("static/pct_lds.csv"))

library(rethinking)
data("WaffleDivorce")

dat_5m4 <-
	dplyr::left_join(
		WaffleDivorce,
		pct_lds,
		by = c("Location" = "State")
	)

dplyr::glimpse(dat_5m4)
```


